version: 0.2

phases:
  install:
    commands:
      - echo Instalando Node 21 e npm...
      - curl -fsSL https://rpm.nodesource.com/setup_21.x | sudo bash -
      - sudo yum install -y nodejs
  build:
    commands:
      - cd client && npm install --legacy-peer-deps --loglevel=error
      - cd client && VITE_API_URL=http://localhost:8080 npm run build
      - echo Rodando testes unitários
      - npm test
